// src/data/priceData.ts

export const womensWorldPrices = [
  { item: 'Shirt / T Shirt', dryClean: 'Rs. 95', steamIroning: 'Rs. 25', stiffening: 'Rs. 30' },
  { item: 'Shirt (Silk)', dryClean: 'Rs. 105', steamIroning: 'Rs. 25', stiffening: 'NA' },
  { item: 'Shirt (Heavy work)', dryClean: 'Rs. 115', steamIroning: 'Rs. 25', stiffening: 'Rs. 30' },
  { item: 'Top (Plain)', dryClean: 'Rs. 95', steamIroning: 'Rs. 30', stiffening: 'Rs. 30' },
  { item: 'Top (Silk)', dryClean: 'Rs. 105', steamIroning: 'Rs. 40', stiffening: 'NA' },
  { item: 'Top (Heavy Work) *', dryClean: 'Rs. 115', steamIroning: 'Rs. 45', stiffening: 'Rs. 40' },
  { item: 'Trouser / Jeans', dryClean: 'Rs. 105', steamIroning: 'Rs. 25', stiffening: 'Rs. 30' },
  { item: 'Short Kurti (Plain)', dryClean: 'Rs. 119', steamIroning: 'Rs. 30', stiffening: 'NA' },
  { item: 'Short Kurti (Silk)', dryClean: 'Rs. 119', steamIroning: 'Rs. 35', stiffening: 'NA' },
  { item: 'Short Kurti (Work)', dryClean: 'Rs. 129', steamIroning: 'Rs. 40', stiffening: 'NA' },
  { item: 'Only Kurta*', dryClean: 'Rs. 149', steamIroning: 'Rs. 40', stiffening: 'Rs. 30' },
  { item: 'Short Kameez*', dryClean: 'Rs. 129', steamIroning: 'Rs. 45', stiffening: 'NA' },
  { item: 'Long Kameez*', dryClean: 'Rs. 199', steamIroning: 'Rs. 65', stiffening: 'NA' },
  { item: 'Shalwar', dryClean: 'Rs. 95', steamIroning: 'Rs. 45', stiffening: 'Rs. 35' },
  { item: 'Pyjama (Plain)', dryClean: 'Rs. 99', steamIroning: 'Rs. 30', stiffening: 'Rs. 30' },
  { item: 'Pyjama (Silk)', dryClean: 'Rs. 119', steamIroning: 'Rs. 30', stiffening: 'NA' },
  { item: 'Palazzo (Plain)', dryClean: 'Rs. 129', steamIroning: 'Rs. 35', stiffening: 'NA' },
  { item: 'Palazzo (Silk)', dryClean: 'Rs. 149', steamIroning: 'Rs. 35', stiffening: 'NA' },
  { item: 'Palazzo (Heavy)*', dryClean: 'Rs. 199', steamIroning: 'Rs. 45', stiffening: 'NA' },
  { item: 'Short Skirt', dryClean: 'Rs. 99', steamIroning: 'Rs. 25', stiffening: 'NA' },
  { item: 'Long Skirt', dryClean: 'Rs. 129', steamIroning: 'Rs. 45', stiffening: 'NA' },
  { item: 'Woolen Sweater', dryClean: 'Rs. 179', steamIroning: 'Rs. 45', stiffening: 'NA' },
  { item: 'Dress*', dryClean: 'Rs. 179', steamIroning: 'Rs. 55', stiffening: 'NA' },
  { item: 'Blazer / coat', dryClean: 'Rs. 249', steamIroning: 'Rs. 100', stiffening: 'NA' },
  { item: 'Lehenga (Plain)', dryClean: 'Rs. 249', steamIroning: 'Rs. 99/149', stiffening: 'NA' },
  { item: 'Lehenga (Silk)*', dryClean: 'Rs. 279', steamIroning: 'Rs. 99/149', stiffening: 'NA' },
  { item: 'Lehenga (Heavy)*', dryClean: 'Rs. 399/499', steamIroning: 'Rs. 199', stiffening: 'NA' },
  { item: 'Lehenga (5 Layers) *', dryClean: 'Rs. 699/799', steamIroning: 'Rs. 299', stiffening: 'NA' },
  { item: 'Chaniya*', dryClean: 'Rs. 399', steamIroning: 'Rs. 195.', stiffening: 'NA' },
  { item: 'Choli*', dryClean: 'Rs. 199', steamIroning: 'Rs. 110', stiffening: 'NA' },
  { item: 'Ghagra (Plain)', dryClean: 'Rs. 399', steamIroning: 'Rs. 80', stiffening: 'NA' },
  { item: 'Ghagra (Multi Colored) *', dryClean: 'Rs. 499', steamIroning: 'Rs. 100', stiffening: 'NA' },
  { item: 'Jump Suit', dryClean: 'Rs. 249', steamIroning: 'Rs. 100', stiffening: 'NA' },
  { item: 'Long Burqa', dryClean: 'Rs. 279', steamIroning: 'Rs. 120', stiffening: 'NA' },
  { item: 'Anarkali Kurta*', dryClean: 'Rs. 399', steamIroning: 'Rs149', stiffening: 'NA' },
  { item: 'Gown (Plain)*', dryClean: 'Rs. 349', steamIroning: 'Rs. 140', stiffening: 'NA' },
  { item: 'Gown (Medium)*', dryClean: 'Rs. 449', steamIroning: 'Rs. 190', stiffening: 'NA' },
  { item: 'Gown (Heavy)*', dryClean: 'Rs. 549', steamIroning: 'Rs. 250', stiffening: 'NA' },
  { item: 'Gown (6 layers) *', dryClean: 'Rs. 799', steamIroning: 'Rs. 375', stiffening: 'NA' },
  { item: 'Cotton Saree', dryClean: 'Rs. 299', steamIroning: 'Rs. 100', stiffening: 'Rs. 160' },
  { item: 'Netted Saree', dryClean: 'Rs.249/279', steamIroning: 'Rs.100', stiffening: 'NA' },
  { item: 'Silk Saree', dryClean: 'Rs. 329', steamIroning: 'Rs. 100', stiffening: 'NA' },
  { item: 'Banaras Saree', dryClean: 'Rs349', steamIroning: 'Rs100', stiffening: 'NA' },
  { item: 'Semi Pattu', dryClean: 'Rs. 399', steamIroning: 'Rs. 100', stiffening: 'NA' },
  { item: 'Pattu Saree', dryClean: 'Rs.449', steamIroning: 'Rs. 100', stiffening: 'NA' },
  { item: 'Plain Blouse', dryClean: 'Rs.99', steamIroning: 'Rs. 25', stiffening: 'NA' },
  { item: 'Heavy Work Blouse', dryClean: 'Rs199', steamIroning: 'Rs. 30', stiffening: 'NA' },
  { item: 'Dupatta (Plain)', dryClean: 'Rs.99', steamIroning: 'Rs. 30', stiffening: 'NA' },
  { item: 'Dupatta (Heavy)', dryClean: 'Rs. 129', steamIroning: 'Rs. 35', stiffening: 'NA' },
  { item: 'Stoal', dryClean: 'Rs. 110', steamIroning: 'Rs. 30', stiffening: 'NA' },
  { item: 'Scarf', dryClean: 'Rs. 110', steamIroning: 'Rs30', stiffening: 'NA' },
  { item: 'Petticoat (Single color, single layer)', dryClean: 'Rs. 135', steamIroning: 'Rs. 65', stiffening: 'NA' },
  { item: 'Leggings', dryClean: 'Rs. 95', steamIroning: 'Rs. 50', stiffening: 'NA' },
  { item: 'Night wear (Single Pc)', dryClean: 'Rs. 125', steamIroning: 'Rs. 50', stiffening: 'NA' },
  { item: 'Under Garment', dryClean: 'Rs. 90', steamIroning: 'Rs. 35', stiffening: 'NA' },
  { item: 'Slip', dryClean: 'Rs. 100', steamIroning: 'Rs. 55', stiffening: 'NA' },
  { item: 'Socks', dryClean: 'Rs. 40', steamIroning: 'NA', stiffening: 'NA' },
  { item: 'Stockings', dryClean: 'Rs. 60', steamIroning: 'NA', stiffening: 'NA' },
];

export const mensWorldPrices = [
  { item: 'Shirt / T Shirt (Plain)', dryClean: 'Rs. 95', steamIroning: 'Rs.25', stiffening: 'RS. 60' },
  { item: 'Shirt (Silk)', dryClean: 'Rs.95', steamIroning: 'Rs. 30', stiffening: 'NA' },
  { item: 'Shirt (Heavy work)', dryClean: 'Rs129', steamIroning: 'Rs. 45', stiffening: 'Rs. 55' },
  { item: 'Pull Over', dryClean: 'Rs. 140', steamIroning: 'Rs. 50', stiffening: 'Rs. 70' },
  { item: 'Kurta (Plain)', dryClean: 'Rs. 120', steamIroning: 'Rs. 45', stiffening: 'Rs. 70' },
  { item: 'Kurta (Silk)', dryClean: 'Rs. 180', steamIroning: 'Rs. 55', stiffening: 'NA' },
  { item: 'Kurta (Heavy work)', dryClean: 'Rs. 210', steamIroning: 'Rs. 65', stiffening: 'Rs. 100' },
  { item: 'Pyjama (Plain)', dryClean: 'RS. 99', steamIroning: 'Rs. 45', stiffening: 'Rs. 55' },
  { item: 'Pyjama (Silk)', dryClean: 'Rs. 105', steamIroning: 'Rs. 55', stiffening: 'NA' },
  { item: 'Shalwar (Plain)', dryClean: 'Rs. 95', steamIroning: 'Rs. 55', stiffening: 'Rs. 55' },
  { item: 'Shalwar (Silk)', dryClean: 'Rs. 110', steamIroning: 'Rs. 65', stiffening: 'NA' },
  { item: 'Trouser / Jeans / Chinos', dryClean: 'Rs. 105', steamIroning: 'Rs. 30', stiffening: 'Rs. 55' },
  { item: 'Trouser (Wool)', dryClean: 'Rs. 105', steamIroning: 'Rs. 45', stiffening: 'NA' },
  { item: 'Shorts', dryClean: 'Rs. 75', steamIroning: 'Rs. 30', stiffening: 'Rs. 55' },
  { item: 'Pants 3/4th\'s', dryClean: 'Rs. 90', steamIroning: 'Rs. 30', stiffening: 'Rs. 55' },
  { item: 'Track Pant', dryClean: 'Rs. 105', steamIroning: 'Rs. 30', stiffening: 'NA' },
  { item: 'Dhoti (Cotton)', dryClean: 'Rs. 160', steamIroning: 'Rs. 60', stiffening: 'Rs. 80' },
  { item: 'Dhoti (Silk)', dryClean: 'Rs. 180', steamIroning: 'Rs. 80', stiffening: 'NA' },
  { item: 'Lungi', dryClean: 'Rs. 100', steamIroning: 'Rs. 30', stiffening: 'NA' },
  { item: 'Boiler Suit', dryClean: 'Rs. 180', steamIroning: 'Rs. 100', stiffening: 'NA' },
];

export const mensSpecialCarePrices = [
  { item: 'Jump Suit', washingPrice: 'Rs. 180', ironingPrice: 'Rs. 100' },
  { item: 'Prince Coat / Jodhpur', washingPrice: 'Rs. 370', ironingPrice: 'Rs. 120' },
  { item: 'Blazer / Coat', washingPrice: 'Rs. 245', ironingPrice: 'Rs. 120' },
  { item: 'Waist Coat', washingPrice: 'Rs. 190', ironingPrice: 'Rs. 80' },
  { item: 'Suit (2 Piece)', washingPrice: 'Rs. 345', ironingPrice: 'Rs. 150' },
  { item: 'Suit (3 Piece)', washingPrice: 'Rs. 499', ironingPrice: 'Rs. 220' },
  { item: 'Woolen Overcoat (Knee Length) *', washingPrice: 'Rs. 1350', ironingPrice: 'Rs. 550' },
  { item: 'Sherwani (Plain)', washingPrice: 'Rs. 550', ironingPrice: 'Rs. 150' },
  { item: 'Sherwani (Work)*', washingPrice: 'Rs. 650', ironingPrice: 'Rs. 250' },
  { item: 'Bohra Long Jacket/Thob (Arabi Jhubba)', washingPrice: 'Rs. 250', ironingPrice: 'Rs. 120' },
  { item: 'Zipper*', washingPrice: 'Rs. 200', ironingPrice: 'Rs. 55' },
  { item: 'Puffer Jacket / Windcheater*', washingPrice: 'Rs. 550', ironingPrice: 'NA' },
  { item: 'Hoody (Normal)', washingPrice: 'Rs. 190', ironingPrice: 'Rs. 60' },
  { item: 'Hoody (Heavy)*', washingPrice: 'Rs. 250', ironingPrice: 'Rs. 60' },
  { item: 'Sweater', washingPrice: 'Rs. 180', ironingPrice: 'Rs. 60' },
  { item: 'Denim Jacket', washingPrice: 'Rs. 350', ironingPrice: 'Rs. 95' },
  { item: 'Leather Jacket*', washingPrice: 'Rs. 590', ironingPrice: 'NA' },
  { item: 'Leather Jacket with Fur*', washingPrice: 'Rs. 690', ironingPrice: 'NA' },
  { item: 'Leather Jacket (Heavy)*', washingPrice: 'Rs. 790', ironingPrice: 'NA' },
  { item: 'Tie / Bow', washingPrice: 'Rs. 70', ironingPrice: 'Rs. 35' },
  { item: 'Handkerchief', washingPrice: 'Rs. 30', ironingPrice: 'Rs. 15' },
];

export const perKGPricing = [
  { type: 'Wash and Steam Iron per KG', price: 'Rs. 129' },
  { type: 'Wash and Fold per KG', price: 'Rs. 99' },
];

export const shoesBagsPrices = [
  { item: 'Canvas Shoe*', washingPrice: 'Rs. 329' },
  { item: 'Sports Shoe*', washingPrice: 'Rs. 349' },
  { item: 'Ankle’s*', washingPrice: 'Rs. 399' },
  { item: 'Leather Shoe*', washingPrice: 'Rs. 449' },
  { item: 'Boots', washingPrice: 'Rs. 699' },
  { item: 'Biker’s Long Shoes*', washingPrice: 'Rs. 999' },
  { item: 'Formal shoes', washingPrice: 'Rs. 329' },
  { item: 'Ladies Purse (Small)*', washingPrice: 'Rs. 249' },
  { item: 'Ladies Purse (Large)*', washingPrice: 'Rs. 399' },
  { item: 'Laptop bag*', washingPrice: 'Rs. 349' },
  { item: 'Duffle bag*', washingPrice: 'Rs. 399' },
  { item: 'Trolley bag (Small)*', washingPrice: 'Rs. 499' },
  { item: 'Trolley bag (Medium)*', washingPrice: 'Rs. 599' },
  { item: 'Suit Case*', washingPrice: 'Rs. 999' },
];

export const curtainsPrices = [
  { item: 'Curtain – SFT', cotton: 'Rs. 30', medium: 'Rs. 35', heavy: 'Rs. 45' },
];

export const curtainsPerKg = [
  { item: 'Curtains per KG (Small)', price: 'Rs. 279' },
];

export const householdPrices = [
  { item: 'Bedsheet (Single)*', dryClean: 'Rs. 149', steamIroning: 'Rs. 50' },
  { item: 'Bedsheet (Double)*', dryClean: 'Rs. 199', steamIroning: 'Rs. 65' },
  { item: 'Blanket / Quilt Single', dryClean: 'Rs. 349', steamIroning: 'NA' },
  { item: 'Blanket / Quilt Double', dryClean: 'Rs. 449', steamIroning: 'NA' },
  { item: 'Apron', dryClean: 'Rs. 100', steamIroning: 'NA' },
  { item: 'Comforter Single', dryClean: 'Rs. 349', steamIroning: 'NA' },
  { item: 'Comforter Double', dryClean: 'Rs. 449', steamIroning: 'NA' },
  { item: 'Bath Towel (Small / Medium / Large)', dryClean: 'Rs. 79 / 99 / 110', steamIroning: 'NA' },
  { item: 'Pillow Cover (Small / Large)', dryClean: 'Rs. 49 / 69', steamIroning: 'NA' },
  { item: 'Fancy Cushion Covers (Small / Large)', dryClean: 'Rs. 79 / 99', steamIroning: 'NA' },
  { item: 'Table Cloth (Small / Large)', dryClean: 'Rs. 99 / 129', steamIroning: 'NA' },
  { item: 'Pillow (Small / Large / Conical)', dryClean: 'Rs. 129 / 149 / 189', steamIroning: 'NA' },
  { item: 'Cushions (Small / Large)', dryClean: 'Rs. 149 / 169 / 199', steamIroning: 'NA' },
  { item: 'Shawl (Light / Heavy)', dryClean: 'Rs. 129/ 179', steamIroning: 'NA' },
  { item: 'Shawl wool (Small / large)', dryClean: 'Rs. 149 / 199', steamIroning: 'NA' },
];

export const carpetRugPrices = [
  { item: 'Carpet * 2ft X 2ft', washing: 'Rs. 349' },
  { item: 'Carpet * 3ft X 3ft', washing: 'Rs. 449' },
  { item: 'Carpet * 6ft X ft', washing: 'Rs. 899' },
  { item: 'Rug* 2ft x 1ft', washing: 'Rs. 299' },
  { item: 'Rug* 2ft x 2ft', washing: 'Rs. 499' },
  { item: 'Rug* 2ft x 3ft', washing: 'Rs. 699' },
  { item: 'Door Mat*', washing: 'Rs. 69' },
];

export const childrenWorldPrices = [
  { item: 'Kid’s Shirt / T-shirt', dryClean: 'Rs. 79', steamIroning: 'Rs. 20', stiffening: 'Rs. 25' },
  { item: 'Kid’s shirt (Work)', dryClean: 'Rs. 99', steamIroning: 'Rs. 30', stiffening: 'NA' },
  { item: 'Kid’s pant / Jeans', dryClean: 'Rs. 99', steamIroning: 'Rs. 20', stiffening: 'Rs. 25' },
  { item: 'Kid’s Coat', dryClean: 'Rs. 149', steamIroning: 'Rs. 69', stiffening: 'NA' },
  { item: 'Kid’s Sherwani', dryClean: 'Rs. 199', steamIroning: 'Rs. 89', stiffening: 'NA' },
  { item: 'Kid’s Waist coat', dryClean: 'Rs. 129', steamIroning: 'Rs. 25', stiffening: 'NA' },
  { item: 'Baby Kurta (Plain)', dryClean: 'Rs. 69', steamIroning: 'Rs. 20', stiffening: 'Rs. 30' },
  { item: 'Baby Pyjama / Shalwar', dryClean: 'Rs. 99', steamIroning: 'Rs. 20', stiffening: 'Rs. 20' },
  { item: 'Baby Frock*', dryClean: 'Rs. 149', steamIroning: 'Rs. 40', stiffening: 'NA' },
  { item: 'Baby Fancy Dress*', dryClean: 'Rs. 199', steamIroning: 'Rs. 60', stiffening: 'NA' },
  { item: 'Baby Night wear (2 Pc)', dryClean: 'Rs. 129', steamIroning: 'Rs. 60', stiffening: 'NA' },
  { item: 'Baby under garment', dryClean: 'Rs. 30', steamIroning: 'NA', stiffening: 'NA' },
];

export const softToyPrices = [
  { item: 'Soft Toy (Small)', washing: 'Rs. 99' },
  { item: 'Soft Toy - 1 Ft', washing: 'Rs. 199' },
  { item: 'Soft Toy - 2 Ft', washing: 'Rs. 299' },
  { item: 'Soft Toy - 3 Ft', washing: 'Rs. 399' },
  { item: 'Soft Toy - 4 Ft', washing: 'Rs. 499' },
  { item: 'Soft Toy - 5 Ft', washing: 'Rs. 599' },
  { item: 'Soft Toy – 6 Ft', washing: 'Rs. 699' },
];